module.exports = {
  SIGN_IN: 'SIGN_IN',
  RECEIVE_LOGIN: 'RECEIVE_LOGIN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  ADD_GROUP: 'ADD_GROUP',
  ADD_USER_GROUP: 'ADD_USER_GROUP',
  SAVE_CONTACT: 'SAVE_CONTACT',
  RECEIVE_CONTACT: 'RECEIVE_CONTACT',
  REMOVE_CONTACT: 'REMOVE_CONTACT',
  SAVE_GROUP: 'SAVE_GROUP',
  RECEIVE_GROUP: 'RECEIVE_GROUP',
  SAVE_GROUP_USER: 'SAVE_GROUP_USER',
  SAVE_MESSAGE: 'SAVE_MESSAGE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  GOOGLE: 'GOOGLE',
  LOGOUT: 'LOGOUT'
};
